### ISSUE TITLE
Working 

### ISSUE THREAD

**Issue by UAsoftwaredeveloper** [mb300sd/Bitcoin-Tool#2]
it is not starting

**Comment by mb300sd** [comment]
It's pretty ancient code and the protocol has been updated under it a number of times. I wrote it mostly as a learning exercise.

**Comment by UAsoftwaredeveloper** [comment]
I want my mined bitcoin

**Comment by mb300sd** [comment]
This tool was never used to mine bitcoin.

**Comment by UAsoftwaredeveloper** [comment]
Not closed I have transferred bitcoin to my bitcoin wallet of coin switch
